trigger: none

pool:
  vmImage: windows-latest

steps:
- checkout: self
  submodules: false
  persistCredentials : true
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $value = Get-Content README.md
      Write-Host $value
      # $value2 = Get-Content $(System.DefaultWorkingDirectory)/ASP.NET_MVCModel-3.1-/README.md
      # Write-Host $value2


# ASP.NET_MVCModel-3.1-
